SELECT YEAR(SALES_DATE) AS YEAR,
	   MONTH(SALES_DATE) AS MONTH,
       GENDER,
       COUNT(DISTINCT A.USER_ID) AS USERS -- 동일한 조합 -> 하나의 판매 데이터만 존재
FROM USER_INFO A, ONLINE_SALE B
WHERE A.USER_ID = B.USER_ID
GROUP BY YEAR, MONTH, GENDER
HAVING GENDER IS NOT NULL
ORDER BY YEAR, MONTH, GENDER;