SELECT YEAR,
	   MONTH,
       COUNT(*) AS PUCHASED_USERS,
       ROUND((COUNT(*) / (SELECT COUNT(*) FROM USER_INFO WHERE YEAR(JOINED) = "2021")), 1) AS PUCHASED_RATIO
FROM (SELECT DISTINCT
      YEAR(B.SALES_DATE) AS YEAR,
      MONTH(B.SALES_DATE) AS MONTH,
      A.USER_ID
      FROM USER_INFO A JOIN ONLINE_SALE B
	  ON A.USER_ID = B.USER_ID
      AND YEAR(JOINED) = "2021"
      ) C
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH;