SELECT A.ANIMAL_ID,
	   A.ANIMAL_TYPE,
       A.NAME
FROM ANIMAL_INS AS A, ANIMAL_OUTS AS B
WHERE A.ANIMAL_ID = B.ANIMAL_ID
AND A.SEX_UPON_INTAKE REGEXP('Intact')
AND B.SEX_UPON_OUTCOME REGEXP('Spayed|Neutered')
ORDER BY A.ANIMAL_ID;