SELECT CATEGORY,
	   PRICE AS MAX_PRICE,
       -- MAX(PRICE) AS MAX_PRICE, -> 식품 이름 - 제일 비싼 식품이 매치 X
       PRODUCT_NAME
FROM FOOD_PRODUCT
WHERE CATEGORY IN ('과자', '김치', '국', '식용유')
AND PRICE IN (SELECT MAX(PRICE)
              FROM FOOD_PRODUCT
              GROUP BY CATEGORY)
ORDER BY PRICE DESC;